repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        args: ['--maxkb=600']
      - id: check-docstring-first
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
        args: [ --unsafe ]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: trailing-whitespace

  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.14.0
    hooks:
      - id: pretty-format-toml
        args: [--autofix, --no-sort]

  - repo: local
    hooks:
    -   id: formatter
        name: ruff format (local)
        entry: uv run ruff format
        language: system
        types: [python]
    -   id: linter
        name: ruff lint (local)
        entry: uv run ruff check --fix
        language: system
        types: [python]
    -   id: ty
        name: ty (local)
        entry: uv run ty check
        language: system
        types: [python]
