[project]
name = "ape-solidity-starter"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "ape-solidity>=0.8.5"
]

[dependency-groups]
dev = [
  "pre-commit>=4.3.0",
  "ruff>=0.12.12",
  "ty>=0.0.1a20"
]
