name: Python Unit Tests

on:
  push:
    branches: [ main, config-github-actions ]
  pull_request:
    branches: [ main, config-github-actions ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v6
        with:
          version: 0.7.19 # workaround for uv error on ubuntu: sqlite3.OperationalError: no such module: fts5
          python-version: ${{ matrix.python-version }}

      - name: Run tests with pytest
        run: uv run pytest tests
